name: API Tests with Newman

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Install CSV Reporter
        run: npm install -g newman-reporter-csv

      - name: Ensure CSV Reporter is Installed
        run: npm list -g --depth=0 | grep newman-reporter-csv || echo "CSV Reporter not found"

      - name: Ensure Results Directory Exists
        run: mkdir -p results

      - name: Debug - List Files in Repository
        run: ls -R

      - name: Debug - Check Collection and Environment Files
        run: |
          if [ ! -f "Issuer APIS.postman_collection.json" ]; then echo "Collection file not found!"; exit 1; fi
          if [ ! -f "IM_TestNetwork.postman_environment.json" ]; then echo "Environment file not found!"; exit 1; fi

      - name: Run API Tests, Capture Logs, and Generate CSV Report
        run: |
          newman run "Issuer APIS.postman_collection.json" -e "IM_TestNetwork.postman_environment.json" \
            --reporters cli,csv \
            --reporter-csv-export results/results.csv \
            --verbose > results/newman_log.txt 2>&1 || echo "Newman tests failed. Check logs."

      - name: Debug - List Files in Directory
        run: ls -lh results/

      - name: Debug - Check File Content
        run: |
          echo "CSV File Content:"
          cat results/results.csv || echo "CSV file is empty!"
          echo "Log File Content:"
          cat results/newman_log.txt || echo "Log file is empty!"

      - name: Upload Test Reports (CSV & Logs)
        uses: actions/upload-artifact@v4
        with:
          name: newman-test-reports
          path: results/

      - name: Send Email with CSV and Log File
        if: always()  # Ensure email is sent even if tests fail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "API Test Report - Newman"
          body: |
            Hi Team,

            The latest API test run has completed. 

            - ✅ If tests passed, results are attached.
            - ❌ If tests failed, check the attached logs for details.

          to: udhaya.kumar@intainft.com,bharathi.m@intainft.com,srihari.sardena@intainft.com
          from: Newman Alert
          attachments: results/results.csv, results/newman_log.txt
