name: API Tests with Newman

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Install CSV Reporter
        run: npm install -g newman-reporter-csv

      - name: Ensure CSV Reporter is Installed
        run: npm list -g --depth=0 | grep newman-reporter-csv || echo "CSV Reporter not found"

      - name: Ensure Results Directory Exists
        run: mkdir -p results

      - name: Run API Tests, Capture Logs, and Generate CSV Report
        run: |
          newman run tests/postman_collection.json \
            --reporters cli,csv \
            --reporter-csv-export results/results.csv | tee results/newman_log.txt

      - name: Debug - List Files in Directory
        run: ls -R results

      - name: Upload Test Reports (CSV & Logs)
        uses: actions/upload-artifact@v4
        with:
          name: newman-test-reports
          path: results/

      - name: Send Email with CSV and Log File
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "API Test Report - Newman"
          body: |
            Hi Team,

            Please find attached the latest API test report generated by GitHub Actions.

            - CSV Report: results.csv
            - Logs: newman_log.txt

          to: udhaya.kumar@intainft.com,bharathi.m@intainft.com  
          from: Newman Github Alert
          attachments: results/results.csv, results/newman_log.txt
